"""removing the relation between the Users and Letters tables

Revision ID: a5296922502d
Revises: 6c4a2659c70c
Create Date: 2024-07-21 18:58:06.196031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5296922502d'
down_revision: Union[str, None] = '6c4a2659c70c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
