"""removing the relation between the Users and Letters tables plus

Revision ID: a9068d200738
Revises: a5296922502d
Create Date: 2024-07-21 19:00:15.890149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9068d200738'
down_revision: Union[str, None] = 'a5296922502d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('letters_user_id_fkey', 'letters', type_='foreignkey')
    op.drop_column('letters', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('letters', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('letters_user_id_fkey', 'letters', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
