"""Add sent column to Letter table

Revision ID: cf382cf030ae
Revises: be869d1570bc
Create Date: 2024-07-20 14:14:43.608970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf382cf030ae'
down_revision: Union[str, None] = 'be869d1570bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('letters', sa.Column('sent', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('letters', 'sent')
    # ### end Alembic commands ###
